name: work

on:
  schedule:
    # Syntax: https://crontab.guru
    - cron: "11 8 1-31 * *"
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm i --force
      - name: Work
        env:
          committer_email: ${{ vars.COMMITTER_EMAIL }}
          committer_name: ${{ vars.COMMITTER_NAME }}
          token: ${{ secrets.AUTO_COMMITTER_TOKEN }}
        run: |
          date=$(date -u)
          sed -r "s/@@@/$date/" ./reamde.md > ./README.md
          sed -r "s/@@@/$date/" ./src/index.ts > ./src/index-dev.ts
          sed -r "s/@@@/$date/" ./src/app.tes > ./src/app-dev.ts
          sed -r "s/@@@/$date/" ./src/creator.ts > ./src/creator-dev.ts
          git config --global user.email $committer_email
          git config --global user.name $committer_name
          git remote set-url origin "https://x-access-token:$token@github.com/${{ github.repository }}"
          git status
          git add -A
          git commit -a -m "Updated MS AI Bot to $date"          
          git push
